ablaze
	[m][c darkred][b]1.[/b][/c] [p]adj[/p] [p]pred.[/p][/m]
	[m1][c darkslateblue]1)[/c] палаючий, блискаючий[/m]
	[m3][*][ex][lang name="English"]to set ~[/lang] — підпалити[/ex][/*][/m]
	[m1][c darkslateblue]2)[/c] збуджений[/m]
	[m3][*][ex][lang name="English"]~ with anger[/lang] — дуже розгніваний[/ex][/*][/m]
	[m][c darkred][b]2.[/b][/c] [p]adv[/p][/m]
	[m1]у вогні, у полум'ї[/m]
	[m3][*][ex][lang name="English"]to be ~[/lang] — палати[/ex][/*][/m]
able
	[m1][p]adj[/p][/m]
	[m1][c darkslateblue]1)[/c] спроможний, здатний; умілий, вправний[/m]
	[m3][*][ex][lang name="English"]to be ~ (з [p]inf[/p])[/lang] —  бути спроможним, могти[/ex][/*][/m]
	[m3][*][ex][lang name="English"]to be ~ to swim[/lang] — уміти плавати[/ex][/*][/m]
	[m1][c darkslateblue]2)[/c] здібний, талановитий[/m]
	[m3][*][ex][lang name="English"]~ speech[/lang] — талановита промова[/ex][/*][/m]
	[m1][c darkslateblue]3)[/c] [p]юр.[/p] компетентний, правоздатний[/m]
	[m1][c darkslateblue]4)[/c] [p]мор.[/p] з добрими морехідними даними[/m]
abode
	[m][b]I[/b][/m]
	[m1][p]n[/p][/m]
	[m1]житло; оселя, господа; місцеперебування[/m]
	[m3][*][ex][lang name="English"]to take up (to make) one's ~[/lang] — оселитися[/ex][/*][/m]
	[m][b]II[/b][/m]
	[m1][p]past і p.p.[/p] [p]від[/p] <<abide>>[/m]
about
	[m][c darkred][b]1.[/b][/c] [p]adv[/p][/m]
	[m1][c darkslateblue]1)[/c] навкруги, довкола, навколо, кругом, скрізь; в різних місцях[/m]
	[m3][*][ex][lang name="English"]to look ~[/lang] — оглянутися, обдивитися навкруги[/ex][/*][/m]
	[m3][*][ex][lang name="English"]rumours are ~[/lang] — ходять чутки[/ex][/*][/m]
	[m1][c darkslateblue]2)[/c] неподалік, поблизу, недалеко[/m]
	[m3][*][ex][lang name="English"]she is somewhere ~[/lang] — вона десь тут[/ex][/*][/m]
	[m1][c darkslateblue]3)[/c] приблизно, близько, майже[/m]
	[m3][*][ex][lang name="English"]the lecture lasted ~ two hours[/lang] — лекція тривала близько двох годин[/ex][/*][/m]
	[m3][*][ex][lang name="English"]you are ~ right[/lang] — ви, мабуть, маєте рацію[/ex][/*][/m]
	[m3][*][ex][lang name="English"]it is ~ three o'clock[/lang] — зараз близько третьої години[/ex][/*][/m]
	[m1][c darkslateblue]4)[/c] у зворотному напрямі[/m]
	[m3][*][ex][lang name="English"]to face ~[/lang] — обернутися, повернутися [com][i](назад)[/i][/com][/ex][/*][/m]
	[m3][*][ex][lang name="English"]~ turn![/lang] — [p]військ.[/p] кругом![/ex][/*][/m]
	[m3][*][ex][lang name="English"]~ face![/lang] — [p]амер.[/p][p],[/p] [p]військ.[/p] кругом![/ex][/*][/m]
	[m1][c darkslateblue]5)[/c] [p]заст.[/p] в окружності[/m]
	[m3][*][ex][lang name="English"]a mile ~[/lang] — одна миля в окружності[/ex][/*][/m]
	[m3][*][ex][lang name="English"]~ and ~[/lang] — [p]амер.[/p] дуже схоже, однаково[/ex][/*][/m]
	[m3][*][ex][lang name="English"]to be ~[/lang] — [i]а)[/i] збиратися [com][i](щось робити)[/i][/com]; бути зайнятим чимсь[/ex][/*][/m]
	[m3][*][ex][lang name="English"]they were ~ to go home[/lang] — вони збиралися йти додому; [i]б)[/i] бути присутнім[/ex][/*][/m]
	[m3][*][ex][lang name="English"]Mr. Green is not ~[/lang] — пан Грін вийшов[/ex][/*][/m]
	[m][c darkred][b]2.[/b][/c] [p]prep[/p][/m]
	[m1][c darkslateblue]1)[/c] про[/m]
	[m3][*][ex][lang name="English"]to talk ~ literature[/lang] — говорити про літературу[/ex][/*][/m]
	[m1][c darkslateblue]2)[/c] навколо, поблизу[/m]
	[m3][*][ex][lang name="English"]look ~ you[/lang] — подивіться навколо себе[/ex][/*][/m]
	[m1][c darkslateblue]3)[/c] по[/m]
	[m3][*][ex][lang name="English"]to walk ~ the streets[/lang] — ходити по вулицях[/ex][/*][/m]
	[m1][c darkslateblue]4)[/c] близько [com][i](про час)[/i][/com][/m]
	[m3][*][ex][lang name="English"]he came ~ four[/lang] — він прийшов близько четвертої години[/ex][/*][/m]
	[m1][c darkslateblue]5)[/c] через, за, з приводу, у зв'язку з[/m]
	[m3][*][ex][lang name="English"]they quarrel ~ trifles[/lang] — вони сваряться за дрібниці[/ex][/*][/m]
	[m3][*][ex][lang name="English"]there is something wrong ~ it[/lang] — тут щось не так[/ex][/*][/m]
	[m1][c darkslateblue]6)[/c] при, з[/m]
	[m3][*][ex][lang name="English"]she has no money ~ her[/lang] — у неї при собі немає грошей[/ex][/*][/m]
	[m][c darkred][b]3.[/b][/c] [p]v[/p] [p]мор.[/p][/m]
	[m1]змінювати курс; повертати[/m]
absent
	[m][b]I[/b][/m]
	[m1][p]adj[/p][/m]
	[m1][c darkslateblue]1)[/c] відсутній[/m]
	[m3][*][ex][lang name="English"]he is ~[/lang] — він відсутній, його немає[/ex][/*][/m]
	[m1][c darkslateblue]2)[/c] неуважний, неуважливий[/m]
	[m][b]II[/b][/m]
	[m1][p]v[/p] [p]refl[/p][/m]
	[m1][c darkslateblue]1)[/c] відлучитися [com][i](піти, поїхати)[/i][/com][/m]
	[m1][c darkslateblue]2)[/c] бути відсутнім[/m]
	[m3][*][ex][lang name="English"]to ~ oneself from [p]smth.[/p][/lang] — ухилятися від чогось[/ex][/*][/m]
absinth
absinthe
	[m1][p]n[/p][/m]
	[m1][c darkslateblue]1)[/c] полин[/m]
	[m1][c darkslateblue]2)[/c] абсент [com][i](напій)[/i][/com][/m]
abuse
	[m][b]I[/b][/m]
	[m1][p]n[/p][/m]
	[m1][c darkslateblue]1)[/c] лайка; образа[/m]
	[m3][*][ex][lang name="English"]to exchange ~[/lang] — ображати один одного[/ex][/*][/m]
	[m1][c darkslateblue]2)[/c] жорстоке [com][i](погане)[/i][/com] поводження[/m]
	[m1][c darkslateblue]3)[/c] неправильне вживання[/m]
	[m1][c darkslateblue]4)[/c] зловживання [com][i](чимсь — of)[/i][/com][/m]
	[m1][c darkslateblue]5)[/c] [p]тех.[/p] експлуатація з порушенням правил[/m]
	[m][b]II[/b][/m]
	[m1][p]v[/p][/m]
	[m1][c darkslateblue]1)[/c] лаяти, ображати; ганьбити[/m]
	[m1][c darkslateblue]2)[/c] жорстоко [com][i](погано)[/i][/com] поводитися[/m]
	[m1][c darkslateblue]3)[/c] зловживати[/m]
	[m1][c darkslateblue]4)[/c] неправильно вживати[/m]
	[m1][c darkslateblue]5)[/c] [p]pass.[/p] бути введеним в оману, бути обманутим[/m]
	[m1][c darkslateblue]6)[/c] розбещувати [com][i](малолітніх)[/i][/com][/m]
	[m1][c darkslateblue]7)[/c] зловживати[/m]
	[m3][*][ex][lang name="English"]to ~ one's position[/lang] — зловживати своїм становищем[/ex][/*][/m]
	[m1][c darkslateblue]8)[/c] [p]тех.[/p] експлуатувати з порушенням правил[/m]
abaft
	[m1][p]мор.[/p][/m]
	[m][c darkred][b]1.[/b][/c] [p]adv[/p][/m]
	[m1]на кормі; у напрямі до корми; ззаду[/m]
	[m][c darkred][b]2.[/b][/c] [p]prep[/p][/m]
	[m1]позаду, за[/m]
	[m3][*][ex][lang name="English"]~ the beam[/lang] — позаду траверсу[/ex][/*][/m]
add
	[m1][p]v[/p][/m]
	[m1][c darkslateblue]1)[/c] додавати; прилучати; приєднувати; надавати[/m]
	[m3][*][ex][lang name="English"]to ~ salt[/lang] — підсолювати[/ex][/*][/m]
	[m3][*][ex][lang name="English"]to ~ fuel to the fire[/lang] — підливати масла у вогонь[/ex][/*][/m]
	[m1][c darkslateblue]2)[/c] [p]мат.[/p] додавати[/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]in[/b][/lang] — включати[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]to[/b][/lang] — додавати, добавляти, збільшувати[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]together[/b], ~ [b]up[/b][/lang] — підраховувати, знаходити суму, додавати[/c][/m]
back
	[m][c darkred][b]1.[/b][/c] [p]n[/p][/m]
	[m1][c darkslateblue]1)[/c] спина[/m]
	[m3][*][ex][lang name="English"]to lie on one's ~[/lang] — лежати на спині[/ex][/*][/m]
	[m3][*][ex][lang name="English"]to fall on one's ~[/lang] — упасти навзнак[/ex][/*][/m]
	[m1][c darkslateblue]2)[/c] спинка [com][i](стільця тощо)[/i][/com][/m]
	[m1][c darkslateblue]3)[/c] спинний хребет; поперек[/m]
	[m1][c darkslateblue]4)[/c] задня [com][i](зворотна)[/i][/com] сторона; задній план[/m]
	[m1][c darkslateblue]5)[/c] виворіт, спід, підкладка[/m]
	[m1][c darkslateblue]6)[/c] гребінь [com][i](хвилі, пагорба)[/i][/com][/m]
	[m1][c darkslateblue]7)[/c] корінець [com][i](книги)[/i][/com]; спинка [com][i](палітурки)[/i][/com][/m]
	[m1][c darkslateblue]8)[/c] обух[/m]
	[m1][c darkslateblue]9)[/c] [p]гірн.[/p] найвищий рівень [com][i](виробки)[/i][/com][/m]
	[m1][c darkslateblue]10)[/c] [p]геол.[/p] висячий бік [com][i](пласта)[/i][/com][/m]
	[m1][c darkslateblue]11)[/c] [p]спорт.[/p] захисник [com][i](у футболі)[/i][/com][/m]
	[m1][c darkslateblue]12)[/c] корито; чан; великий бак[/m]
	[m2][c red]◊[/c] [c dodgerblue][lang name="English"]~ to ~[/lang] — впритул[/c][/m]
	[m2][c red]◊[/c] [c dodgerblue][lang name="English"]to turn one's ~ upon (on) [p]smb.[/p][/lang] — відвернутися від когось, порвати стосунки з кимсь[/c][/m]
	[m2][c red]◊[/c] [c dodgerblue][lang name="English"]to put (to set) [p]smb.[/p]'s ~ up[/lang] — розгнівати когось[/c][/m]
	[m2][c red]◊[/c] [c dodgerblue][lang name="English"]to be at the ~ of [p]smb.[/p][/lang] — підтримувати когось, бути на чиємусь боці[/c][/m]
	[m][c darkred][b]2.[/b][/c] [p]adj[/p][/m]
	[m1][c darkslateblue]1)[/c] задній[/m]
	[m3][*][ex][lang name="English"]~ entrance[/lang] — чорний хід[/ex][/*][/m]
	[m3][*][ex][lang name="English"]~ edge (margin)[/lang] — [p]друк.[/p] внутрішнє [com][i](корінцеве)[/i][/com] поле[/ex][/*][/m]
	[m3][*][ex][lang name="English"]~ elevation[/lang] — вигляд ззаду, задній фасад[/ex][/*][/m]
	[m3][*][ex][lang name="English"]~ tooth[/lang] — кутній зуб[/ex][/*][/m]
	[m3][*][ex][lang name="English"]~ vowel[/lang] — [p]фон.[/p] голосний заднього ряду[/ex][/*][/m]
	[m1][c darkslateblue]2)[/c] віддалений, дальній[/m]
	[m3][*][ex][lang name="English"]~ street[/lang] — віддалена [com][i](глуха)[/i][/com] вулиця[/ex][/*][/m]
	[m3][*][ex][lang name="English"]~ road[/lang] — путівець[/ex][/*][/m]
	[m3][*][ex][lang name="English"]~ shop[/lang] — підсобна майстерня[/ex][/*][/m]
	[m1][c darkslateblue]3)[/c] зворотний[/m]
	[m3][*][ex][lang name="English"]~ action[/lang] — задній хід[/ex][/*][/m]
	[m3][*][ex][lang name="English"]~ current[/lang] — зворотна течія[/ex][/*][/m]
	[m1][c darkslateblue]4)[/c] запізнілий, відсталий; старий[/m]
	[m3][*][ex][lang name="English"]a ~ number (issue) of a magazine[/lang] — старий номер журналу[/ex][/*][/m]
	[m1][c darkslateblue]5)[/c] [p]амер.[/p] затриманий, прострочений [com][i](про платіж:)[/i][/com][/m]
	[m3][*][ex][lang name="English"]~ payment[/lang] — прострочений платіж[/ex][/*][/m]
	[m1][c darkslateblue]6)[/c] [p]військ.[/p] тиловий[/m]
	[m3][*][ex][lang name="English"]~ line defence[/lang] — оборона тилової смуги [com][i](лінії)[/i][/com][/ex][/*][/m]
	[m3][*][ex][lang name="English"]~ areas[/lang] — [p]військ.[/p] тили, тилові райони[/ex][/*][/m]
	[m][c darkred][b]3.[/b][/c] [p]adv[/p][/m]
	[m1][c darkslateblue]1)[/c] ззаду, позаду[/m]
	[m3][*][ex][lang name="English"]keep ~![/lang] — не підходьте!, відійдіть назад![/ex][/*][/m]
	[m3][*][ex][lang name="English"]~ home[/lang] — знову вдома [com][i](на батьківщині)[/i][/com][/ex][/*][/m]
	[m3][*][ex][lang name="English"]to sit ~[/lang] — зручно усістися, відкинутися на спинку крісла[/ex][/*][/m]
	[m1][c darkslateblue]2)[/c] назад, у зворотному напрямі[/m]
	[m3][*][ex][lang name="English"]when will you be ~?[/lang] — коли ви повернетеся?[/ex][/*][/m]
	[m3][*][ex][lang name="English"]~ and forth[/lang] — назад і вперед; туди й назад[/ex][/*][/m]
	[m1][c darkslateblue]3)[/c] знову[/m]
	[m1][c darkslateblue]4)[/c] осторонь, віддалік[/m]
	[m3][*][ex][lang name="English"]the house stood ~ from the road[/lang] — будинок стояв осторонь шляху[/ex][/*][/m]
	[m1][c darkslateblue]5)[/c] тому[/m]
	[m3][*][ex][lang name="English"]a few years ~[/lang] — кілька років тому[/ex][/*][/m]
	[m1][c darkslateblue]6)[/c] указує на зворотну дію[/m]
	[m3][*][ex][lang name="English"]to answer ~[/lang] — заперечувати[/ex][/*][/m]
	[m3][*][ex][lang name="English"]to talk ~[/lang] — огризатися[/ex][/*][/m]
	[m3][*][ex][lang name="English"]to love ~[/lang] — відповідати взаємністю[/ex][/*][/m]
	[m3][*][ex][lang name="English"]to go ~ from one's word[/lang] — відцуратися від свого слова [com][i](від своєї обіцянки)[/i][/com][/ex][/*][/m]
	[m][c darkred][b]4.[/b][/c] [p]v[/p][/m]
	[m1][c darkslateblue]1)[/c] підтримувати, підкріпляти[/m]
	[m1][c darkslateblue]2)[/c] закріпляти [com][i](якір)[/i][/com][/m]
	[m1][c darkslateblue]3)[/c] зміцнювати, підпирати[/m]
	[m1][c darkslateblue]4)[/c] субсидувати, фінансувати[/m]
	[m1][c darkslateblue]5)[/c] рухатися у зворотному напрямі; відступати, задкувати; осаджувати; іти заднім ходом[/m]
	[m1][c darkslateblue]6)[/c] сідати на коня, їхати верхи[/m]
	[m1][c darkslateblue]7)[/c] класти на підкладку[/m]
	[m1][c darkslateblue]8)[/c] прилягати ззаду[/m]
	[m1][c darkslateblue]9)[/c] [p]амер.[/p][p],[/p] [p]розм.[/p] носити на спині[/m]
	[m1][c darkslateblue]10)[/c] бути спинкою [com][i](підкладкою)[/i][/com]; бути фоном[/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]down[/b][/lang] — відступати, відмовлятися[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]off[/b][/lang] — гальмувати, сповільнювати[/c][/m]
	[m3][*][ex][lang name="English"]~ off![/lang] — відчепися![/ex][/*][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]out of[/b][/lang] — ухилятися від[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]up[/b][/lang] — підтримувати; давати задній хід[/c][/m]
	[m2][c red]◊[/c] [c dodgerblue][lang name="English"]to ~ the wrong horse[/lang] — помилитися, прорахуватися, поставити не на того коня[/c][/m]
come
	[m1][p]v[/p] [com][i]([p]past[/p] came; [p]p.p.[/p] come)[/i][/com][/m]
	[m1][c darkslateblue]1)[/c] приходити; приїжджати; прибувати; підходити[/m]
	[m1][c darkslateblue]2)[/c] іти, їхати[/m]
	[m1][c darkslateblue]3)[/c] підходити, наближатися [com][i](часто ~ to)[/i][/com][/m]
	[m1][c darkslateblue]4)[/c] доходити, досягати[/m]
	[m1][c darkslateblue]5)[/c] наставати, приходити[/m]
	[m3][*][ex][lang name="English"]spring came[/lang] — настала весна[/ex][/*][/m]
	[m1][c darkslateblue]6)[/c] з'являтися, виникати[/m]
	[m1][c darkslateblue]7)[/c] траплятися; відбуватися[/m]
	[m3][*][ex][lang name="English"]how did it ~ that you quarrelled?[/lang] — як це трапилося, що ви посварилися?[/ex][/*][/m]
	[m1][c darkslateblue]8)[/c] виходити, робитися[/m]
	[m3][*][ex][lang name="English"]things will ~ all right[/lang] — усе буде гаразд[/ex][/*][/m]
	[m1][c darkslateblue]9)[/c] походити; бути родом [com][i](походженням)[/i][/com][/m]
	[m3][*][ex][lang name="English"]he ~s from Kyiv[/lang] — він родом з Києва[/ex][/*][/m]
	[m1][c darkslateblue]10)[/c] діставатися[/m]
	[m1][c darkslateblue]11)[/c] проростати, сходити, рости[/m]
	[m1][c darkslateblue]12)[/c] [com][i]у наказовому способі — вигук, що передає запрошення, спонукання, підбадьорювання тощо[/i][/com][/m]
	[m3][*][ex][lang name="English"]~![/lang] — ну![/ex][/*][/m]
	[m3][*][ex][lang name="English"]~, don't be so obstinate[/lang] — нубо, не впирайся![/ex][/*][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]about[/b][/lang] — відбуватися, траплятися[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]across[/b][/lang] — випадково зустріти когось, наштовхнутися на когось[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]after[/b][/lang] — іти за[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]again[/b][/lang] — повертатися; [p]амер.[/p][p],[/p] [p]розм.[/p] повторювати[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]along![/b][/lang] — ходімо!, поспішайте![/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]asunder[/b][/lang] — розпадатися на частини[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]at[/b][/lang] — добиратися до когось; накидатися на когось; домогтися чогось[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]away[/b][/lang] — піти [com][i](геть)[/i][/com]; відламуватися[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]back[/b][/lang] — повертатися; пригадуватися; прийти до пам'яті[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]before[/b][/lang] — бути важливішим; постати перед[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]between[/b][/lang] — втручатися[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]by[/b][/lang] — проходити мимо; діставати, досягати; [p]амер.[/p][p],[/p] [p]розм.[/p] заходити [com][i](кудись)[/i][/com][/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]down[/b][/lang] — спускатися, опускатися; падати [com][i](про дощ, сніг)[/i][/com][/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]down on [com][i](upon)[/i][/com][/b][/lang] — накидатися; лаяти[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]for[/b][/lang] — заходити за[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]forward[/b][/lang] — виходити уперед, висуватися[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]in[/b][/lang] — входити, заходити; приходити, прибувати [com][i](про транспорт)[/i][/com]; вступати у[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]into[/b][/lang] — вступати у[/c][/m]
	[m3][*][ex][lang name="English"]to ~ into notice[/lang] — привертати увагу[/ex][/*][/m]
	[m3][*][ex][lang name="English"]to ~ into sight[/lang] — з'явитися[/ex][/*][/m]
	[m3][*][ex][lang name="English"]to ~ into the world[/lang] — народитися[/ex][/*][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]of[/b][/lang] — виникати; виходити[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]off[/b][/lang] — зникати; відриватися; мати успіх; відбуватися; сходити; злізати[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]on[/b][/lang] — насуватися; з'являтися [com][i](на сцені)[/i][/com]; наставати; зростати; досягати успіхів[/c][/m]
	[m3][*][ex][lang name="English"]he is coming on well in his studies[/lang] — він робить великі успіхи у навчанні[/ex][/*][/m]
	[m3][*][ex][lang name="English"]~ on![/lang] — мерщій!; далі!, ходімо![/ex][/*][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]out[/b][/lang] — виходити; з'являтися [com][i](у пресі)[/i][/com]; виявлятися; розпускатися [com][i](про квіти тощо)[/i][/com]; застрайкувати; виводитися [com][i](про плями)[/i][/com][/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]round[/b][/lang] — заходити ненадовго; змінюватися на краще; змінювати [com][i](свою)[/i][/com] думку[/c][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]to[/b][/lang] — доходити до; дорівнювати[/c][/m]
	[m3][*][ex][lang name="English"]to ~ to life[/lang] — прийти до пам'яті, ожити[/ex][/*][/m]
	[m3][*][ex][lang name="English"]to ~ to light[/lang] — виявлятися[/ex][/*][/m]
	[m3][*][ex][lang name="English"]to ~ to oneself[/lang] — опритомніти[/ex][/*][/m]
	[m3][*][ex][lang name="English"]to ~ to pass[/lang] — відбуватися, траплятися[/ex][/*][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]up[/b][/lang] — підійматися; виникати; сходити [com][i](про рослину)[/i][/com][/c][/m]
	[m3][*][ex][lang name="English"]~ up to[/lang] — досягати рівня, підходити[/ex][/*][/m]
	[m2][c brown]□[/c] [c royalblue][lang name="English"]~ [b]upon[/b][/lang] — випадково зустріти; несподівано напасти[/c][/m]
	[m2][c red]◊[/c] [c dodgerblue][lang name="English"]to ~ easy to [p]smb.[/p][/lang] — не завдавати труднощів комусь[/c][/m]
	[m2][c red]◊[/c] [c dodgerblue][lang name="English"]to ~ natural[/lang] — бути природним[/c][/m]
	[m2][c red]◊[/c] [c dodgerblue][lang name="English"]to ~ short of [p]smth.[/p][/lang] — не вистачати чогось[/c][/m]
	[m2][c red]◊[/c] [c dodgerblue][lang name="English"]to ~ to the point[/lang] — говорити по суті справи[/c][/m]
	[m2][c red]◊[/c] [c dodgerblue][lang name="English"]to ~ true[/lang] — здійснюватися[/c][/m]
	[m2][c red]◊[/c] [c dodgerblue][lang name="English"]to ~ to bat[/lang] — [p]амер.[/p] зустрітися з важкою проблемою [com][i](з тяжким випробуванням)[/i][/com][/c][/m]
purplish
	[m1][p]adj[/p][/m]
	[m1]багрянистий; з фіалковим відтінком[/m]
purply
	[m1][p]див.[/p] <<purplish>>[/m]
rhotacism
	[m1][p]n[/p][/m]
	[m1][c darkslateblue]1)[/c] [p]лінгв.[/p] ротацизм[/m]
	[m1][c darkslateblue]2)[/c] утрируване вимовляння звука {r}[/m]
